### ISSUE TITLE
Cursor hiding support

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/mosaic#389]

**Comment by JakeWharton** [comment]
Funny enough I want this primarily for the recordings of our demos where it's distracting. Not sure I actually need it for anything. Although surely some users will want this.

The real question is what's the API for this? Presumably over time you might want to change the visibility depending on what the app is doing. What's an analogous thing in Android? Hiding the system UI?

**Comment by EpicDima** [comment]
I think you can try to turn off the cursor for the demo via `input.sh` where the first command will be `ESC[?25l`

https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797#common-private-modes

**Comment by JakeWharton** [comment]
True! A good workaround for now.

**Comment by EpicDima** [comment]
After merging the [pull request](https://github.com/JakeWharton/mosaic/pull/442) with `RawMode`, we can try to hide the cursor for `runMosaic` at the start, and show it again after completion so that the user is not afraid of the disappeared cursor. Inside the Mosaic application, the cursor only gets in the way, it seems to me.

**Comment by JakeWharton** [comment]
I don't think doing so requires raw mode, but long term I'd like cursor control be more nuanced than this. For accepting input, for example, we want the cursor to be displayed. It also will help indicate focus whenever a focus manager is implemented. It's possible that we can disable it and only show it for focused input elements, but that also means providing some kind of input element out-of-the-box.

**Comment by EpicDima** [comment]
Yes, in fact, it is possible without raw mode, I meant that there is a similar mechanism that turns off raw mode when exiting, which adds control. If we do this now, I think ctrl + c will instantly close the program and will not return the standard cursor view.
I'm worried about moving the cursor for input fields, it seems easier to do this through a custom element (just one rectangle character that appears and disappears every 500 ms), because otherwise it can complicate the rendering process, where we now rely on the cursor always being at the end.

**Comment by JakeWharton** [comment]
Yeah, maybe. But terminals also allow customization of the cursor and blink rate so it might create an uncanny valley. I guess we'll cross that bridge when we get there.

**Comment by JakeWharton** [comment]
* libvaxis: hides by default

    https://github.com/rockorager/libvaxis/blob/fcdeb321feccc1b2b62391c1e257c385a799810e/src/Vaxis.zig#L330

* ratatui: hides by default

    https://github.com/ratatui/ratatui/blob/e02947be6185643f906a97c453540676eade3f38/src/terminal/terminal.rs#L396-L397

* bubbletea: hides by default

    https://github.com/charmbracelet/bubbletea/blob/b2e983a1f12f62e268ba9ff22174a4b8b632134a/tea.go#L716-L717

* textual: hides by default

    https://github.com/Textualize/textual/blob/db3fda928ba3f4807f01ae24ecee260ce6206b1b/src/textual/drivers/linux_driver.py#L246

* ink: hides by default

    https://github.com/vadimdemedes/ink/blob/7fedab06770eb6199aafe06163f9c47884b88f58/src/components/App.tsx#L129-L131


I think we should hide by default!

**Comment by EpicDima** [comment]
By the way, I have a [branch](https://github.com/EpicDima/mosaic/tree/epicdima/no_last_empty_line) to delete an empty line at the bottom. The branch is waiting for a [pull request](https://github.com/JakeWharton/mosaic/pull/394) with a decrease in the number of canvases.
